test:
	@GOEXPERIMENT=jsonv2 go test ./...

testacc:
	@GOEXPERIMENT=jsonv2 TF_ACC=1 go test ./...

checks:
	@GOEXPERIMENT=jsonv2 go fmt ./...
	@GOEXPERIMENT=jsonv2 go vet ./...
	@staticcheck ./...
	@gosec ./...
	@goimports -w internal

fmt:
	@terraform fmt -recursive
	@find ./internal/sdkv2provider -type f -name '*_test.go' | sort -u | xargs -I {} terrafmt fmt {}
	@find ./docs/data-sources -type f -name '*.md' | sort -u | xargs -I {} terrafmt fmt {}
